name: Build and Push Custom Vikunja

on:
  schedule:
    - cron: '0 4 * * *'  # Rebuild daily at 4 AM UTC
  workflow_dispatch:     # Allows manual triggering
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/mpwhiten/vikunja-curl:latest
